export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST'
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS'
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL'

export const GET_USER_BLOGS_REQUEST = 'GET_USER_BLOGS_REQUEST'
export const GET_USER_BLOGS_SUCCESS = 'GET_USER_BLOGS_SUCCESS'
export const GET_USER_BLOGS_FAIL = 'GET_USER_BLOGS_FAIL'

export const GET_ALL_BLOGS_REQUEST = 'GET_ALL_BLOGS_REQUEST'
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS'
export const GET_ALL_BLOGS_FAIL = 'GET_ALL_BLOGS_FAIL'
