export const TOAST_ACTION_REQUEST = 'TOAST_ACTION_REQUEST'
export const TOAST_ACTION_SUCCESS = 'TOAST_ACTION_SUCCESS'
export const TOAST_ACTION_FAIL = 'TOAST_ACTION_FAIL'
export const TOAST_ACTION_CLEAR = 'TOAST_ACTION_CLEAR'
